# Generated by Django 4.2.7 on 2023-12-08 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='discreption',
            new_name='discription',
        ),
    ]
