# Generated by Django 4.2.7 on 2023-12-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0002_rename_discreption_post_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='discription',
            new_name='description',
        ),
    ]
